version: '3.8'

services:
  nestjs:
    container_name: nestjs_back
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - backend_network

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistica
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root
      #volumes:
      #- ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
